version: '3.9'

services:
  jupyter:
    build: .
    image: whisper_docker_compose:latest
    environment:
      JUPYTER_TOKEN: "docker"
    ports:
      - 8888:8888
    volumes:
      - ./project:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
